# strongSwan configuration file

charon {
   start-scripts {
      creds = swanctl --load-creds
      conns = swanctl --load-conns
      pools = swanctl --load-pools
   }
   filelog {
      stderr {
         default = 1
      }
   }
   eap-dynamic {
      prefer_user = yes
      preferred = md5, tls
   }
   plugins {
        vici {
            # Expose VICI on TCP port 4502 on all interfaces
            socket = tcp://0.0.0.0:4502

            # Optional (recommended): restrict to localhost for safety
            # socket = tcp://127.0.0.1:4502
        }
    }
}

libtls {
  version_max = 1.3
  suites = TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384
}

swanctl {
  socket = tcp://127.0.0.1:4502
}
